# Generated by Django 5.0.6 on 2024-06-26 02:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('fechaCompra', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Galon',
            fields=[
                ('idGalon', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='IdGalon')),
                ('kg', models.IntegerField(blank=True, null=True, verbose_name='kg')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Marca')),
                ('nombreMarca', models.CharField(max_length=50, verbose_name='Nombre de Marca')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_boleta',
            fields=[
                ('id_detalle_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('id_boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.galon')),
            ],
        ),
        migrations.AddField(
            model_name='galon',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.marca', verbose_name='marca'),
        ),
    ]
